import "./globals.css";
import Link from "next/link";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { LogIn } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-black-100  fixed top-7 right-14 w-full z-50 flex justify-end">
          <Link href='/login'>
            <LogIn className="h-5 w-5" />
          </Link>
        </header>
        {children}
        
      </body>
    </html>
  );
}
